name:                fractran
version:             0.1.0.0
github:              "githubuser/fractran"
license:             BSD3
author:              "Vsevolod Shchipunov"
maintainer:          "vsevolod.shchipunov@gmail.com"
copyright:           "2019 Vsevolod Shchipunov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aleisteratreides/fractran#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  fractran-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fractran

tests:
  fractran-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fractran
    - hspec
    - QuickCheck
